backend:
  name: git-gateway
  repo: BlackMuttMedia/heartofdarkness
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    extension: mdx
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "content-pages",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Key", name: "key", widget: "string" }
      - label: "Parent Key"
        name: "parentKey"
        widget: "relation"
        collection: "pages"
        searchFields: ["title", "templateKey", "key"]
        displayFields: ["title"]
        valueField: "key"
        required: false
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - label: "Points"
        name: "points"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Point", name: "point", widget: "markdown" }
      - {
          label: "After Points",
          name: "afterPoints",
          widget: "markdown",
          required: false,
        }
